// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package splunk.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Splunk module

	public static boolean getEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("Splunk.Enabled");
	}

	public static java.lang.String getEndpoint()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Splunk.Endpoint");
	}

	/**
	* See https://docs.splunk.com/DocumentationStatic/JavaLogging/1.6.2/com/splunk/logging/HttpEventCollectorSender.html#DefaultBatchCount
	*/
	public static java.lang.Long getMaxEventsBatchCount()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("Splunk.MaxEventsBatchCount");
	}

	/**
	* See https://docs.splunk.com/DocumentationStatic/JavaLogging/1.6.2/com/splunk/logging/HttpEventCollectorSender.html#DefaultBatchSize
	*/
	public static java.lang.Long getMaxEventsBatchSize()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("Splunk.MaxEventsBatchSize");
	}

	/**
	* One of NONE | CRITICAL | ERROR | WARNING | INFO | DEBUG | TRACE
	*/
	public static java.lang.String getMinimalLogLevel()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Splunk.MinimalLogLevel");
	}

	/**
	* Splunk application token
	*/
	public static java.lang.String getToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Splunk.Token");
	}
}