// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package splunk.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Splunk module

	public static java.lang.String getEndpoint()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Splunk.Endpoint");
	}

	/**
	* One of NONE | CRITICAL | ERROR | WARNING | INFO | DEBUG | TRACE
	*/
	public static java.lang.String getMinimalLogLevel()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Splunk.MinimalLogLevel");
	}

	/**
	* Splunk application token
	*/
	public static java.lang.String getToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Splunk.Token");
	}
}